# Generated by Django 2.1.7 on 2019-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemapimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='googlemapimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
